"""
Git operations for auto-coder: repo init, .gitignore creation, auto-commit.

Uses the git binary from the trellis conda environment.
"""

import subprocess
import threading
from pathlib import Path

import shutil as _shutil
GIT_BIN = _shutil.which("git") or "/usr/bin/git"

# Timeout in seconds for any single git command
_GIT_TIMEOUT = 30

# Lock to serialize all git-mutating operations and prevent concurrent
# git index corruption when multiple tasks commit near-simultaneously.
_git_lock = threading.RLock()

# .gitignore: deny-all by default, whitelist code & config files only.
# Heavy data directories are explicitly blocked BEFORE the !*/ rule
# so git never wastes time traversing them.
_GITIGNORE_CONTENT = """\
# ============================================================
# Auto-generated by auto-coder. Deny-all, whitelist code+config.
# ============================================================

# ------ Explicitly block heavy / data directories first ------
# (must come BEFORE !*/ so git never traverses them)
results*/
gt_meshes*/
aligned_cache/
fid_cache/
output*/
test/
logs/
*.npz
*.npy
*.ply
*.obj
*.glb
*.stl
*.off
*.bin
*.pth
*.pt
*.ckpt
*.safetensors
*.png
*.jpg
*.jpeg
*.bmp
*.gif
*.tiff
*.mp4
*.avi
*.zip
*.tar
*.gz
*.bz2
*.so
*.o
*.a
*.dylib
__pycache__/
node_modules/
.venv/
venv/
*.pyc
*.pyo
*.egg-info/
dist/
build/
.cache/
.claude/
.worktrees/

# Ignore everything by default
*

# But allow traversing into subdirectories (only those not blocked above)
!*/

# ------ Python files ------
!*.py

# ------ Config files ------
!*.json
!*.yaml
!*.yml
!*.toml
!*.cfg
!*.ini
!*.txt
!*.md
!.gitignore
"""


def _run_git(project_dir: Path, *args: str, check: bool = True,
             timeout: int = _GIT_TIMEOUT) -> subprocess.CompletedProcess:
    """Run a git command in project_dir with a timeout."""
    cmd = [GIT_BIN] + list(args)
    return subprocess.run(
        cmd,
        cwd=str(project_dir),
        capture_output=True,
        text=True,
        check=check,
        timeout=timeout,
    )


def ensure_git_repo(project_dir: Path) -> None:
    """Initialise a git repo and ensure .gitignore uses our deny-all template."""
    with _git_lock:
        try:
            git_dir = project_dir / ".git"
            gitignore = project_dir / ".gitignore"

            if not git_dir.exists():
                _run_git(project_dir, "init")
                print(f"  [git] Initialised repo in {project_dir}", flush=True)

            # Always overwrite .gitignore to ensure deny-all template is in place
            gitignore.write_text(_GITIGNORE_CONTENT)
            print("  [git] Wrote .gitignore (py+config whitelist)", flush=True)

            # Initial commit if repo has no commits yet
            result = _run_git(project_dir, "rev-parse", "HEAD", check=False)
            if result.returncode != 0:
                _run_git(project_dir, "add", "-A")
                _run_git(project_dir, "commit", "-m", "Initial commit (auto-coder)",
                         check=False)
                print("  [git] Created initial commit", flush=True)
        except (subprocess.TimeoutExpired, subprocess.SubprocessError, OSError) as e:
            print(f"  [git] Warning: ensure_git_repo failed: {e}", flush=True)


# ──────────────────────────────────────────────────────────
# Worktree isolation
# ──────────────────────────────────────────────────────────

WORKTREE_DIR = ".worktrees"


def create_worktree(project_dir: Path, task_id: int) -> Path:
    """Create a git worktree for a task, returning the worktree path.

    The worktree is created under project_dir/.worktrees/task_{task_id}
    on a new branch named 'task-{task_id}'.
    """
    with _git_lock:
        wt_base = project_dir / WORKTREE_DIR
        wt_base.mkdir(parents=True, exist_ok=True)
        wt_path = wt_base / f"task_{task_id}"
        branch_name = f"task-{task_id}"

        # Remove stale worktree if it exists
        if wt_path.exists():
            _run_git(project_dir, "worktree", "remove", "--force",
                     str(wt_path), check=False)

        # Delete stale branch if it exists
        _run_git(project_dir, "branch", "-D", branch_name, check=False)

        _run_git(project_dir, "worktree", "add", "-b", branch_name,
                 str(wt_path))
        print(f"  [git] Created worktree for task #{task_id} at {wt_path}",
              flush=True)
        return wt_path


def merge_worktree(project_dir: Path, task_id: int) -> bool:
    """Merge a task's worktree branch back into the current branch.

    Returns True if the merge succeeded, False otherwise.
    """
    with _git_lock:
        branch_name = f"task-{task_id}"
        try:
            result = _run_git(project_dir, "merge", branch_name,
                              "--no-edit", check=False)
            if result.returncode == 0:
                print(f"  [git] Merged worktree branch {branch_name}",
                      flush=True)
                return True
            else:
                print(f"  [git] Warning: merge of {branch_name} failed: "
                      f"{result.stderr.strip()}", flush=True)
                # Abort the failed merge
                _run_git(project_dir, "merge", "--abort", check=False)
                return False
        except (subprocess.TimeoutExpired, subprocess.SubprocessError,
                OSError) as e:
            print(f"  [git] Warning: merge_worktree failed: {e}", flush=True)
            return False


def cleanup_worktree(project_dir: Path, task_id: int) -> None:
    """Remove the worktree and its branch for a task."""
    with _git_lock:
        wt_path = project_dir / WORKTREE_DIR / f"task_{task_id}"
        branch_name = f"task-{task_id}"
        try:
            if wt_path.exists():
                _run_git(project_dir, "worktree", "remove", "--force",
                         str(wt_path), check=False)
            _run_git(project_dir, "branch", "-D", branch_name, check=False)
            print(f"  [git] Cleaned up worktree for task #{task_id}",
                  flush=True)
        except (subprocess.TimeoutExpired, subprocess.SubprocessError,
                OSError) as e:
            print(f"  [git] Warning: cleanup_worktree failed: {e}",
                  flush=True)


# ──────────────────────────────────────────────────────────
# Git-based file conflict detection (fallback when worktree isolation is off)
# ──────────────────────────────────────────────────────────

def get_changed_files(project_dir: Path, before_hash: str, after_hash: str) -> list[str]:
    """Return list of files changed between two commits using git diff --name-only."""
    try:
        result = _run_git(project_dir, "diff", "--name-only",
                          before_hash, after_hash, check=False)
        if result.returncode == 0 and result.stdout.strip():
            return [f.strip() for f in result.stdout.strip().splitlines() if f.strip()]
    except (subprocess.TimeoutExpired, subprocess.SubprocessError, OSError):
        pass
    return []


def get_file_diff(project_dir: Path, commit_hash: str, filepath: str) -> str:
    """Return the diff for a specific file in a commit."""
    try:
        result = _run_git(project_dir, "diff",
                          f"{commit_hash}~1", commit_hash, "--", filepath,
                          check=False)
        if result.returncode == 0:
            return result.stdout.strip()
    except (subprocess.TimeoutExpired, subprocess.SubprocessError, OSError):
        pass
    return ""


def get_head_hash(project_dir: Path) -> str | None:
    """Return the current HEAD commit hash, or None on failure."""
    try:
        result = _run_git(project_dir, "rev-parse", "HEAD", check=False)
        if result.returncode == 0:
            return result.stdout.strip()
    except (subprocess.TimeoutExpired, subprocess.SubprocessError, OSError):
        pass
    return None


def detect_file_conflicts(
    project_dir: Path,
    results: list[dict],
    before_hash: str | None = None,
) -> list[dict]:
    """Detect file conflicts between tasks using git diff --name-only.

    Only useful when worktree isolation is disabled — tasks commit to the
    same branch sequentially and may touch overlapping files.

    Args:
        project_dir: Path to the git repository.
        results: List of task result dicts, each with 'task_id' and
                 optionally 'commit_hash'.
        before_hash: The HEAD hash recorded before the wave started.
                     Used as the base for diffing each task's changes.

    Returns:
        List of conflict dicts, each containing:
          - 'files': list of overlapping file paths
          - 'task_ids': tuple of (task_id_a, task_id_b)
          - 'diffs': dict mapping filepath -> diff text for each overlap
    """
    if not before_hash:
        return []

    # Build a mapping: task_id -> set of changed files
    task_files: dict[int, set[str]] = {}
    task_hashes: dict[int, str] = {}
    for r in results:
        commit_hash = r.get("commit_hash")
        if not commit_hash:
            continue
        tid = r["task_id"]
        changed = get_changed_files(project_dir, before_hash, commit_hash)
        if changed:
            task_files[tid] = set(changed)
            task_hashes[tid] = commit_hash

    # Find pairwise overlaps
    conflicts = []
    task_ids = sorted(task_files.keys())
    for i, tid_a in enumerate(task_ids):
        for tid_b in task_ids[i + 1:]:
            overlap = task_files[tid_a] & task_files[tid_b]
            if overlap:
                # Collect diffs for overlapping files
                diffs = {}
                for fpath in sorted(overlap):
                    diff_a = get_file_diff(project_dir, task_hashes[tid_a], fpath)
                    diff_b = get_file_diff(project_dir, task_hashes[tid_b], fpath)
                    diffs[fpath] = f"--- Task #{tid_a} ---\n{diff_a}\n--- Task #{tid_b} ---\n{diff_b}"
                conflicts.append({
                    "files": sorted(overlap),
                    "task_ids": (tid_a, tid_b),
                    "diffs": diffs,
                })

    return conflicts


def auto_commit(project_dir: Path, message: str) -> str | None:
    """Stage all tracked changes and commit.

    Returns the full commit hash if a commit was made, or None otherwise.
    Never raises — failures are logged and swallowed so the pipeline
    is never blocked by git issues.
    """
    with _git_lock:
        try:
            _run_git(project_dir, "add", "-A")

            # Check if there is anything to commit
            status = _run_git(project_dir, "status", "--porcelain", check=False)
            if not status.stdout.strip():
                return None

            result = _run_git(project_dir, "commit", "-m", message, check=False)
            if result.returncode == 0:
                rev = _run_git(project_dir, "rev-parse", "HEAD", check=False)
                full_hash = rev.stdout.strip() if rev.returncode == 0 else None
                short = (full_hash[:7] if full_hash else "?")
                print(f"  [git] Committed ({short}): {message}", flush=True)
                return full_hash
            return None
        except subprocess.TimeoutExpired:
            print(f"  [git] Warning: auto_commit timed out ({_GIT_TIMEOUT}s)", flush=True)
            return None
        except (subprocess.SubprocessError, OSError) as e:
            print(f"  [git] Warning: auto_commit failed: {e}", flush=True)
            return None
